apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - context: .
    image: docker.io/venksrinkav/venky-hello-world
deploy:
  kubectl:
    manifests:
    - manifests/helloworld_secret.yaml
    - manifests/helloworld_deployment.yaml
    - manifests/helloworld_service.yaml
    - manifests/helloworld_ingress.yaml
